#!/usr/bin/env python3
"""Vendor the 3L design system at a pinned commit (plan D18).

The design system lives in its own repo (github.com/mjrskiles/3L-design). This
copies its CSS and fonts into the site at a recorded SHA, so the site builds from
committed files with no submodule and no network at build time. CI re-runs this
and fails on any diff — same "commit the artifact, drift-check it" idiom the
figure pipeline uses.

It also DERIVES assets/css/ds/theme-auto.css from the upstream .theme-dark block.
The design system has no prefers-color-scheme support (its themes are class-based
so both can render on one page), and hand-copying those declarations would both
duplicate color decisions outside roles.css — which its DECISIONS #9 forbids — and
go stale the moment a provisional hex is corrected. Deriving keeps one source.

Usage:
  sync_design.py                 sync at the SHA in data/design-system.yaml
  sync_design.py --ref <sha>     sync at a new SHA and record it
  sync_design.py --source <path> read from a local checkout instead of cloning
"""
import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PIN_FILE = ROOT / "data" / "design-system.yaml"
CSS_OUT = ROOT / "assets" / "css" / "ds"
FONT_OUT = ROOT / "static" / "fonts"

UPSTREAM = "https://github.com/mjrskiles/3L-design.git"
DEFAULT_LOCAL = ROOT.parent / "design-system"

# Copied verbatim. Order matters downstream (baseof.html bundles tokens before
# anything that consumes them); this is just the set.
CSS_FILES = ["tokens.css", "roles.css", "fonts.css", "type.css"]


def run(cmd, **kw):
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kw).stdout


def read_pin() -> str:
    if not PIN_FILE.exists():
        sys.exit(f"sync_design: no pin file at {PIN_FILE}; pass --ref to create one")
    for line in PIN_FILE.read_text().splitlines():
        if line.strip().startswith("commit:"):
            return line.split(":", 1)[1].strip().strip("\"'")
    sys.exit(f"sync_design: no `commit:` key in {PIN_FILE}")


def write_pin(sha: str, subject: str) -> None:
    PIN_FILE.parent.mkdir(parents=True, exist_ok=True)
    PIN_FILE.write_text(
        "# Pinned 3L design system revision. Regenerate the vendored copy with\n"
        "#   make design\n"
        "# CI re-runs it and fails on drift, so this file and assets/css/ds/ agree.\n"
        f"repo: {UPSTREAM}\n"
        f"commit: {sha}\n"
        f"subject: {subject!r}\n"
    )


def source_tree(source: str | None, ref: str, tmp: Path) -> Path:
    """A checkout of the design system at `ref`, read-only."""
    local = Path(source) if source else DEFAULT_LOCAL
    if local.is_dir():
        # Export the pinned ref, not the working tree — a dirty sibling checkout
        # must never leak into the vendored copy.
        work = tmp / "src"
        work.mkdir()
        archive = tmp / "src.tar"
        with archive.open("wb") as fh:
            subprocess.run(["git", "-C", str(local), "archive", ref], check=True, stdout=fh)
        shutil.unpack_archive(str(archive), str(work), format="tar")
        return work
    run(["git", "clone", "--quiet", UPSTREAM, str(tmp / "clone")])
    run(["git", "-C", str(tmp / "clone"), "checkout", "--quiet", ref])
    return tmp / "clone"


def derive_theme_auto(roles_css: str, sha: str) -> str:
    """Re-emit the .theme-dark declarations under a prefers-color-scheme query."""
    m = re.search(r"^\.theme-dark\s*\{", roles_css, re.MULTILINE)
    if not m:
        sys.exit("sync_design: no `.theme-dark {` block in upstream roles.css")
    start = m.end()
    depth, i = 1, start
    while i < len(roles_css) and depth:
        if roles_css[i] == "{":
            depth += 1
        elif roles_css[i] == "}":
            depth -= 1
        i += 1
    if depth:
        sys.exit("sync_design: unbalanced braces in upstream .theme-dark block")
    body = roles_css[start : i - 1].strip("\n")
    indented = "\n".join(("  " + ln) if ln.strip() else ln for ln in body.splitlines())
    return (
        f"/* GENERATED by tools/sync_design.py from 3L-design css/roles.css @ {sha[:7]}.\n"
        "   Do not edit — run `make design`.\n\n"
        "   The design system scopes themes to .theme-light / .theme-dark classes so a\n"
        "   page can render both at once. This bridges those roles to the visitor's OS\n"
        "   preference. :root:not(.theme-light) so an explicit light scope still wins. */\n"
        "@media (prefers-color-scheme: dark) {\n"
        "  :root:not(.theme-light) {\n"
        f"{indented}\n"
        "  }\n"
        "}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", help="commit to pin (default: the recorded one)")
    ap.add_argument("--source", help="local design-system checkout")
    args = ap.parse_args()

    ref = args.ref or read_pin()

    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        src = source_tree(args.source, ref, tmp)

        local = Path(args.source) if args.source else DEFAULT_LOCAL
        if local.is_dir():
            sha = run(["git", "-C", str(local), "rev-parse", ref]).strip()
            subject = run(["git", "-C", str(local), "log", "-1", "--format=%s", sha]).strip()
        else:
            sha = run(["git", "-C", str(src), "rev-parse", "HEAD"]).strip()
            subject = run(["git", "-C", str(src), "log", "-1", "--format=%s"]).strip()

        CSS_OUT.mkdir(parents=True, exist_ok=True)
        FONT_OUT.mkdir(parents=True, exist_ok=True)

        header = f"/* VENDORED from 3L-design @ {sha[:7]} — do not edit. Run `make design`. */\n"
        for name in CSS_FILES:
            text = (src / "css" / name).read_text()
            (CSS_OUT / name).write_text(header + text)

        (CSS_OUT / "theme-auto.css").write_text(
            derive_theme_auto((src / "css" / "roles.css").read_text(), sha)
        )

        # Fonts are replaced wholesale: a stale face left behind is a face the
        # browser can still be asked for by a stale @font-face.
        for old in FONT_OUT.glob("*.woff2"):
            old.unlink()
        for f in sorted((src / "fonts").iterdir()):
            if f.suffix == ".woff2" or f.name == "LICENSES.md":
                shutil.copy2(f, FONT_OUT / f.name)

        write_pin(sha, subject)

    css = sorted(p.name for p in CSS_OUT.glob("*.css"))
    fonts = sorted(p.name for p in FONT_OUT.glob("*.woff2"))
    print(f"sync_design: {sha[:7]} — {len(css)} css, {len(fonts)} fonts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
